### ISSUE TITLE
更多的状态

### ISSUE THREAD

**Issue by BNC123** [hu3dao/scroll-view#1]
你好，有没有考虑过实现更多的可能？  （这两个问题深深的困扰着我）
1、已经到底了  这个字样隐藏在底部
2、有没有想过有一种可能，就是用户滑动到底的时候确实是已经到底了，但是还可以继续上拉，有数据则显示，没有就又显示到底了

**Comment by hu3dao** [comment]
我这边给你提供一下思路，后续我这边可以参考一下其他的类似的组件实现这样的需求
需求1：给“已经到底了”的元素设置绝对定位，设置better-scroll的bounce的bottom为true
.load-tips {
  position: absolute;
  width: 100%;
  transform: translateZ(1px);
}
![image](https://user-images.githubusercontent.com/43111870/188860339-2e365bf6-6aba-4c3a-aa92-d230b14ef16f.png)

需求2：把监听finished为true就关闭上拉加载的限制去掉
![image](https://user-images.githubusercontent.com/43111870/188860424-2f24bc4c-6320-4a70-9ff5-32205c759f89.png)

**Comment by BNC123** [comment]
谢谢你的解答，你说的两个思路我走过一次了。
需求1：确实可以隐藏，但实现不了上拉出现，加载完或者显示已经到底了再隐藏。我试过用原本的better-scroll封装进行监听，全部都是针对已经到底了，效果不好（可能是自己技术太菜。尝试有如下：1>、给已经到底了 这个提示根据上拉下拉添加删除类，那个类写了隐藏的样式，效果挺糟糕的。  2>、而且上拉完成以后要立刻调下拉完成并且刷新，因为就算是已经到底了也需要能继续拖动，那么就会有这样一个问题，如果不立刻调上拉完成并且刷新就无法执行下一次上拉了，而立刻执行的话就会有这样的效果：我刚将上拉拖动文字出现，由于已经到底了没有加载数据，所以调加载完成更快，导致文字刚出现就往下隐藏了，哪怕我没松手指，就好像突然往下面坠去）  **下拉的机制是松开手指才调方法，上拉加载是拉动即调**    ### （原本的better-scroll）
需求1还有一个问题，不足一页的数据‘ ’已经到底了‘’ 需要隐藏，我的做法是监听列表高度，不足一页就赋值页面高度，超出就取消（赋值一页高度“已经到底了”字样会在底部隐藏，滚动条也无法拖动的），可以实现，但效果也不好。列表加载到底部应该滚动出下一页时“已经到底了”字样不会马上消失，要过一会，很明显。

需求2：将监听finished为true确实可以将上拉加载的限制去掉，但是不是再上拉就生效，而是先下拉再上拉才能生效  ### （你封装的）

**Comment by BNC123** [comment]
谢谢你的解答，你说的两个思路我走过一次了。
需求1：确实可以隐藏，但实现不了上拉出现，加载完或者显示已经到底了再隐藏。我试过用原本的better-scroll封装进行监听，全部都是针对已经到底了，效果不好（可能是自己技术太菜。
尝试有如下：1>、给已经到底了 这个提示根据上拉下拉添加删除类，那个类写了隐藏的样式，效果挺糟糕的。 
2>、而且上拉完成以后要立刻调下拉完成并且刷新，因为就算是已经到底了也需要能继续拖动，那么就会有这样一个问题，如果不立刻调上拉完成并且刷新就无法执行下一次上拉了，而立刻执行的话就会有这样的效果：我刚将上拉拖动文字出现，由于已经到底了没有加载数据，所以调加载完成更快，导致文字刚出现就往下隐藏了，哪怕我没松手指，就好像突然往下面坠去） 下拉的机制是松开手指才调方法，上拉加载是拉动即调 ### （原本的better-scroll）

需求1还有一个问题，不足一页的数据‘ ’已经到底了‘’ 需要隐藏，我的做法是监听列表高度，不足一页就赋值页面高度，超出就取消（赋值一页高度“已经到底了”字样会在底部隐藏，滚动条也无法拖动的），可以实现，但效果也不好。列表加载到底部应该滚动出下一页时“已经到底了”字样不会马上消失，要过一会，很明显。


需求2：将监听finished为true确实可以将上拉加载的限制去掉，但是不是再上拉就生效，而是先下拉再上拉才能生效 ### （你封装的）

**Comment by BNC123** [comment]
ios永远是我踩得最多的雷，还有一个bug问问你？ 用better-scroll之前我是用vue-pull-to，因为一个bug才想换一下滚动的插件。在ios环境下只要有滚动的地方第一下滚动不了，会先出现滚动条（就好像聚焦效果让它识别滚动的区域一样），然后再滚动就很流畅。

**Comment by BNC123** [comment]
ios永远是我踩得最多的雷，还有一个bug问问你？ 用better-scroll之前我是用vue-pull-to，因为一个bug才想换一下滚动的插件。在ios环境下只要有滚动的地方第一下滚动不了，会先出现滚动条（就好像聚焦效果让它识别滚动的区域一样），然后再滚动就很流畅。

**Comment by BNC123** [comment]
跟你描述了很多，不知道你能不能看懂？难得看到有人对better-scroll进行了二次封装。其实就是两个问题：1、到底了还能加载更多   2、到底了需要隐藏

**Comment by hu3dao** [comment]
试了vue-pull-to提供的实例，已经知道效果了，在ios12的手机上测试暂时没有发现首次无法滚动的情况，单靠better-scroll的文档pullup插件是无法实现它的效果的，我这边再想想如何去实现，到时有结果会告知你

**Comment by BNC123** [comment]
好的，感谢。你说的在ios12的手机上测试暂时没有发现首次无法滚动的情况，给了我一点另外的思路，会不会是我项目或者我封装的vue-pull-to的原因导致的第一下划不动（虽然我找了封装的原因很久才放弃的），我可以再尝试一下了。

**Comment by hu3dao** [comment]
照着vue-pull-to的上拉加载的效果实现了一版，在feature-pullup分支

**Comment by BNC123** [comment]
![2_{MF%YDMN{YJ)2K`$WCZ 7](https://user-images.githubusercontent.com/73508220/189885277-378b1576-2796-4ed8-a426-b44176e0c1c8.png)

![Z2IFAFW4ANAWN)VNC}VDC`Y](https://user-images.githubusercontent.com/73508220/189885324-5c26518a-5aff-4da7-b45f-cd30a9d70c4c.png)

![_7$MUQU4X9U0J $61V9RYF](https://user-images.githubusercontent.com/73508220/189885347-24c47776-d888-4586-9195-20404d06c2c9.png)

**Comment by BNC123** [comment]
感谢你花时间写出了这个项目，我拉下来看了代码，实现了我想要的一些功能，谢谢。（而且代码很规范，厉害）然后我还发现了一些问题并且写了一点相对应的解决办法，然而还有一点没有解决，可能还需要你帮我再看看，或者你有没有更好的方法。（不知道我表达的清不清楚，你能不能看懂？）

问题1：上拉下拉同时开启也就是都为true的时候，（数据不足一页，比如10以内），下拉刷新顶部文字显示状态会有动画，但底部也有，上下两个圆圈一起转（ && 不足一页时底部文字没有隐藏）。
问题2：如果只开启下拉，页面是空白的；手动下拉刷新一次就有了数据。

结果：我做了一些改动，达到了一些效果，但还有一个问题存在（上拉或者下拉滚动到底的时候没有文字显示，直到下一次拖动，我可能需要在上拉或者下拉拖动的时候就为isShowTxt赋值，我现在的赋值时机有些迟了，但我不知道怎样更提前一点）

我的更改如下（有点粗暴）：
想法是这样的：
isShowTxt为true显示顶部提示文字（顶部特殊，就算为true也不会显示出来），为false显示底部提示文字。
刚进入页面通过isShowTxt为true显示顶部这样就不会显示底部了。上拉的时候赋值为false这样底部就出现了，但是上拉自然的滚动到底部不会触发上拉加载所以没赋值成功，直到下一次手动上拉触发，将初始值设置为20你就能看到我说的情况，这就是我没有解决的问题。

**Comment by BNC123** [comment]
mounted这样改的原因是为了只有下拉刷新时数据不显示问题

**Comment by hu3dao** [comment]
![image](https://user-images.githubusercontent.com/43111870/190082536-8eba23cb-937a-4d1a-b74b-e0bd7bdf9297.png)
下拉刷新其实做的操作是将数据重置再重新调用onLoad方法，所以会出现两个圈圈

只有下拉刷新不显示的是因为，没有开启上拉加载时，组件内容不会抛出load事件，这个其实可以在自己的代码（App.vue）的created生命周期里调用请求数据的方法即可

**Comment by BNC123** [comment]
好的，我已经将你封装好的这些用在我的项目中了，去掉了下拉刷新，进入页面刚进入正常，滚动后再回到顶部就是这样了：

**Comment by BNC123** [comment]
好的，这两天将你封装的这个用于实际项目中了，可行的，非常感谢。
